### PR TITLE
allow failures for centos 7 source test

### PR DESCRIPTION
**Pull request by oxyc**
Testing

### CODE REVIEW

**Comment by oxyc** [comment]
Wait what CentOS 7 source build passed the tests (I thought they were failing)

Pass: https://travis-ci.org/geerlingguy/ansible-role-git/jobs/109723284
Fail: https://travis-ci.org/geerlingguy/ansible-role-git/jobs/109271817

**Comment by oxyc** [comment]
@geerlingguy these tests are in reference to your question about `allowed_failures` syntax. I figured the first one should work base on this https://github.com/travis-ci/travis-ci/issues/5113#issuecomment-163140988

**Comment by geerlingguy** [comment]
Well that's strange!

**Comment by oxyc** [comment]
So this seems to be passing already. Closing this PR.

**Pull request closed without merging**
