### PR TITLE
Enable run in 'Check Mode'

### PR DESCRIPTION
**Pull request by janderson2**
The test for the installed version of git must be run in check mode for a valid check of state and to avoid error.

### CODE REVIEW

**Comment by geerlingguy** [comment]
For now, can you use the old setting, for backwards compatibility? I don't want to switch to `always_run` (which only works in 2.2+) until 2.3 is released, because otherwise anyone on 2.0 or 2.1 will get a broken playbook.

**Comment by janderson2** [comment]
I already switched it to always_run as a couple of docker images did not have ansible 2.2 yet.  However, I am running into issues now with the idempotent test failing.  I will take another look later.

**Comment by geerlingguy** [comment]
@janderson2 - Oops, yeah, meant `always_run` instead of `check_mode`, but yes, you've already changed that :)

**Comment by janderson2** [comment]
@geerlingguy - The Idempotence issue was the apt update pre-task.  The apt module has changed it behaviour recently to mark apt updates as changed.  Adding `cache_valid_time` fixes most distributions, however Ubuntu 12.04 is still failing (i.e. appears to be ignoring the `cache_valid_time`).

Looking into the Ubuntu 12.04 issue, I found that the ansible apt module checks if the `/var/lib/apt/periodic/update-success-stamp` file exists, if so it uses that mtime as the last update time.  If it does not exist, it looks at the `/var/lib/apt/lists` directory.  The Dockerfile for the ubuntu 12.04 distro is touching `/var/lib/apt/periodic/update-success-stamp`, but apt-get on 12.04 is not updating this file on update.

PR https://github.com/geerlingguy/docker-ubuntu1204-ansible/pull/1 fixes this by switching from touching the stamp file to touching the `/var/lib/apt/lists' which will get updated on 12.04.

**Comment by geerlingguy** [comment]
@janderson2 - Thanks for pushing through on this! If I forget, please ping me and remind me to tag a release after Travis CI catches up with all my commits today :)

**Comment by janderson2** [comment]
@geerlingguy no worries, and will do.

**Comment by janderson2** [comment]
ping @geerlingguy sorry, I deleted the branch before the tests here completed, but the tests have passed now on merge into master.

**Comment by geerlingguy** [comment]
@janderson2 - Thanks for the reminder! 1.2.1 is out now: https://galaxy.ansible.com/geerlingguy/git/

**Pull request merged**
